name: Create a pullrequest from master to develop (scheduled version)

on:
  push:
    branches:
      - main
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '00 14 * * *'
  # プルリク重複チェック

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if pullrequest exists
        id: check_pullrequest
        run: |
          pullrequest_title="[Auto PullRequest] Merge master into develop"
          base_branch=develop
          echo "::set-output name=count::$(gh pr list -S ${pullrequest_title}' in:title' -B $base_branch | wc -l)"
      - name: Create pullrequest main into develop
        if: ${{ steps.check_pullrequest.outputs.count == 0 }}
        run: |
          gh pr create -B develop -H main -t '[Auto PullRequest] Merge master into develop' -b 'auto create pullrequest'
