name: Create a pullrequest from main to develop (scheduled version)

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '9 15 * * *'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if pullrequest exists
        id: check_pullrequest
        run: |
          echo "::set-output name=count::$(gh pr list -l 'auto pullrequest' -B develop | wc -l)"
          echo "::set-output name=changed::$(git diff --name-only main develop | wc -l)"
      - name: Create pullrequest main into develop
        if: ${{ steps.check_pullrequest.outputs.count == 0 && steps.check_pullrequest.outputs.changed != 0 }}
        run: |
          gh pr create \
            -B develop \
            -H main \
            -t '[Auto PullRequest] Merge main into develop' \
            -b 'auto create pullrequest' \
            -a Lycheejam
